const actions = {
  STORE_CURRENT_USER: "STORE_CURRENT_USER",
  STORE_CURRENT_GIFT: "STORE_CURRENT_CARDS",
  STORE_NEW_CREATED_GIFT: "STORE_NEW_CREATED_GIFT",
  STORE_ALL_GIFTS: "STORE_ALL_GIFTS",
};

export default actions;
